Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,9 +67,12 @@ jobs:
           mkdir -p build
           cd dist
           for folder in */; do
+
+            out="${folder%/}"
+
             echo "Zipping folder: $folder"
-            zip -r "$folder.zip" "$folder" || echo "Failed to zip $folder"
-            mv "$folder.zip" ../build/$folder.zip || echo "Failed to move $folder.zip to build"
+            zip -r "$out.zip" "$folder" || echo "Failed to zip $folder"
+            mv "$out.zip" ../build/$out.zip || echo "Failed to move $folder.zip to build"
           done
 
       - name: List built plugins
